# Match version with the API in package.json
FROM docker.io/actualbudget/actual-server:25.12.0

RUN cd /tmp && npm init -y && npm install @actual-app/api dayjs && \
    cp -r node_modules/* /app/node_modules/ 2>/dev/null || true
